#!/bin/bash
set -e

# Fill out conffile with above values
if [ -f /usr/share/logstash/logstash.template.conf ]; then
        envtpl < /usr/share/logstash/logstash.template.conf > /usr/share/logstash/pipeline/logstash.conf
fi

env2yaml /usr/share/logstash/config/logstash.yml

export LS_JAVA_OPTS="-Dls.cgroup.cpuacct.path.override=/ -Dls.cgroup.cpu.path.override=/ $LS_JAVA_OPTS"

if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]] ; then
  exec logstash "$@"
else
  exec "$@"
fi
