rules_folder: example_rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: localhost
# The Elasticsearch port
es_port: 9200
writeback_index: elastalert_status
writeback_alias: elastalert_alerts

alert_time_limit:
  days: 2

