filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylog/event.log
  tags: ["adserver-event-stg"]
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylog/error.log
  tags: ["adserver-error-stg"]
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylog/access.log
  tags: ["adserver-access-stg"]

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"
